# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7097f95dd666887c0a90b872852a3d5f3075f7a5af448a7a51792964aa1be5bc414e18503c6208dd82a9fcc108c6248c6b9fd71fde47e17e5d8c81baaceff2

test:
  secret_key_base: 6359d6b2d03af7f6d52f81b0e8192208d6b06b1c3ecb1c920a83680f222781ab1e777ca1f028d8c6d8fe52895c4637c312d54d946fc1ad85f3a1af5e3f1f928c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
